version: 2.1

orbs:
  node: circleci/node@4.2.0

jobs:
  build-project:
    executor:
      name: node/default
      tag: '14.2.0'
    steps:
      - checkout
      - node/install:
          node-version: 14.2.0
          npm-version: 6.14.4
      - node/install-packages:
          cache-path: /home/circleci/project/node_modules
          cache-version: v1
          override-ci-command: npm install
      - run:
          name: Lint project
          command: npm run lint
      - run:
          name: Build Vue project
          command: npm run build:vue

workflows:
  build-vaya:
    jobs:
      - build-project